name: Test CF Blue/Green Deploy

# allows to run this directly from gh ui without params
on: [workflow_dispatch]

env:
  CF_API: ${{ secrets.CF_API }}
  CF_ORG: ${{ secrets.CF_ORG }}
  CF_SPACE: ${{ secrets.CF_SPACE }}
  CF_USERNAME: ${{ secrets.CF_USERNAME }}
  CF_PASSWORD: ${{ secrets.CF_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # set cf with blue/green deploy plugin
    - uses: jvalkeal/setup-cf-cli@gh3-work1
      with:
        version: 6.51.0
        plugin-repo: https://plugins.cloudfoundry.org
        plugin-id: blue-green-deploy

    # sanity checks what we actually need later for build and deploy
    - uses: jvalkeal/build-zoo-handler@main
      with:
        ensure-commands: |
          cf
          curl
        ensure-env: |
          CF_API
          CF_ORG
          CF_SPACE
          CF_USERNAME
          CF_PASSWORD

    - name: Build
      run: ./gradlew clean build

    - name: Deploy
      run: cf blue-green-deploy atest4-demo -f .cf/demo-manifest.yml --smoke-test .cf/demo-manifest-smoke.sh
