name: Dispatch Handler Test2

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release version'
        required: true
        default: '0.0.0'
  repository_dispatch:
    types: [build-zoo-handler-build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # base setup
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.6.2
    - uses: jfrog/setup-jfrog-cli@v1
      with:
        version: 1.36.0
      env:
        JF_ARTIFACTORY_SPRING: ${{ secrets.JF_ARTIFACTORY_SECRET_SPRING }}
    - name: Configure JFrog Cli
      run: |
        jfrog rt mvnc \
          --server-id-resolve=spring \
          --server-id-deploy=spring \
          --repo-resolve-releases=libs-spring-dataflow-private-release \
          --repo-resolve-snapshots=libs-spring-dataflow-private-snapshot \
          --repo-deploy-releases=libs-spring-dataflow-private-release \
          --repo-deploy-snapshots=libs-spring-dataflow-private-snapshot \

    # build
    - name: Build and Publish
      run: jfrog rt mvn -U -B clean install

    # zoo
    - name: Notify main controller
      uses: jvalkeal/build-zoo-handler@gh7-work1
      with:
        dispatch-handler-token: ${{ secrets.REPO_ACCESS_TOKEN }}
        dispatch-handler-owner: jvalkeal
        dispatch-handler-repo: atest1
        dispatch-handler-event-type: build-zoo-handler-control
        dispatch-handler-client-payload-data: >
          {
            "event": "build-succeed",
            "prop41": "val41",
            "owner": "jvalkeal",
            "repo": "atest4"
          }
