name: Path Test

on:
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Test, Build, Deploy
    runs-on: ubuntu-latest
    steps:

      - name: PATH1
        run: echo $PATH

      - name: Checkout
        uses: actions/checkout@v2

      - name: PATH2
        run: echo $PATH
        
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: PATH3
        run: echo $PATH

