name: zoo test

on: [push]

jobs:
  build:
    name: Test zoo action
    runs-on: ubuntu-latest
    steps:
    - uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.6.2
    - name: zoo ensure commands
      uses: jvalkeal/build-zoo-handler@master
      with:
        ensure-commands: |
          mvn
          gradle
    - name: zoo ensure env
      uses: jvalkeal/build-zoo-handler@master
      with:
        ensure-env: |
          M2_HOME
    - name: say hi
      run: echo hi
